export const detailsData = [
  {
    id: "detail_001",
    title: "RCパラペット①",
    categoryPath: ["外部", "陸屋根"],
    files: {
      pdf: { path: "/dummy.pdf", size: 245678, pages: 2 },
      dwg: { path: "/dummy.dwg", size: 1234567 },
      dxf: { path: "/dummy.dxf", size: 987654 },
    },
    tags: ["RC", "鉄筋コンクリート", "防水", "パラペット", "笠木"],
    description: "RC造陸屋根のパラペット納まり。防水立上げ150mm、笠木t=60",
    updatedAt: "2024-01-10",
    searchText: "rcぱらぺっと1 外部 陸屋根 鉄筋こんくりーと 防水 笠木",
    relatedIds: ["detail_002"],
  },
  {
    id: "detail_002",
    title: "RCパラペット②",
    categoryPath: ["外部", "陸屋根"],
    files: {
      pdf: { path: "/dummy.pdf", size: 256789, pages: 2 },
      dwg: { path: "/dummy.dwg", size: 1245678 },
      dxf: { path: "/dummy.dxf", size: 998765 },
    },
    tags: ["RC", "鉄筋コンクリート", "防水", "パラペット", "笠木", "水切"],
    description: "RC造陸屋根のパラペット納まり。①の改良版、水切り金物追加",
    updatedAt: "2024-01-12",
    searchText: "rcぱらぺっと2 外部 陸屋根 鉄筋こんくりーと 防水 笠木 水切り",
    relatedIds: ["detail_001"],
    variant: { base: "detail_001", version: 2, changes: "水切り金物の追加" },
  },
  {
    id: "detail_003",
    title: "RC抱き有り",
    categoryPath: ["外部", "開口部"],
    files: {
      pdf: { path: "/dummy.pdf", size: 198765, pages: 1 },
      dwg: { path: "/dummy.dwg", size: 987654 },
      dxf: { path: "/dummy.dxf", size: 876543 },
    },
    tags: ["RC", "開口部", "サッシ", "抱き", "シーリング"],
    description: "RC造開口部のサッシ納まり。RC抱き有り、シーリング処理",
    updatedAt: "2024-01-08",
    searchText: "rc抱き有り 外部 開口部 さっし 鉄筋こんくりーと しーりんぐ",
    relatedIds: ["detail_004"],
  },
  {
    id: "detail_004",
    title: "RC抱き無し",
    categoryPath: ["外部", "開口部"],
    files: {
      pdf: { path: "/dummy.pdf", size: 187654, pages: 1 },
      dwg: null,
      dxf: null,
    },
    tags: ["RC", "開口部", "サッシ", "シーリング"],
    description: "RC造開口部のサッシ納まり。RC抱き無し、直付け",
    updatedAt: "2024-01-05",
    searchText: "rc抱き無し 外部 開口部 さっし 鉄筋こんくりーと しーりんぐ",
    relatedIds: ["detail_003"],
  },
  {
    id: "detail_005",
    title: "木造床納まり①",
    categoryPath: ["内部", "床"],
    files: {
      pdf: { path: "/dummy.pdf", size: 210987, pages: 2 },
      dwg: { path: "/dummy.dwg", size: 1098765 },
      dxf: { path: "/dummy.dxf", size: 987654 },
    },
    tags: ["木造", "床", "フローリング", "断熱材"],
    description: "木造住宅の床納まり。断熱材t=100、フローリング12mm",
    updatedAt: "2024-01-15",
    searchText: "木造 床 ゆか ふろーりんぐ 断熱材",
    relatedIds: [],
  },
  {
    id: "detail_006",
    title: "S造柱脚ベースプレート",
    categoryPath: ["構造", "柱脚"],
    files: {
      pdf: { path: "/dummy.pdf", size: 234567, pages: 3 },
      dwg: { path: "/dummy.dwg", size: 1345678 },
      dxf: { path: "/dummy.dxf", size: 1234567 },
    },
    tags: ["S造", "鉄骨", "柱脚", "ベースプレート", "アンカーボルト"],
    description: "S造の柱脚ベースプレート納まり。M24アンカーボルト",
    updatedAt: "2024-01-13",
    searchText: "s造 鉄骨 てっこつ 柱脚 べーすぷれーと あんかーぼると",
    relatedIds: [],
  },
];

export const categoriesData = [
  {
    id: "cat_001",
    name: "外部",
    children: [
      { id: "cat_001_001", name: "陸屋根", count: 2 },
      { id: "cat_001_002", name: "開口部", count: 2 },
      { id: "cat_001_003", name: "外壁", count: 0 },
      { id: "cat_001_004", name: "基礎", count: 0 },
    ],
  },
  {
    id: "cat_002",
    name: "内部",
    children: [
      { id: "cat_002_001", name: "床", count: 1 },
      { id: "cat_002_002", name: "壁", count: 0 },
      { id: "cat_002_003", name: "天井", count: 0 },
    ],
  },
  {
    id: "cat_003",
    name: "構造",
    children: [
      { id: "cat_003_001", name: "柱脚", count: 1 },
      { id: "cat_003_002", name: "梁", count: 0 },
      { id: "cat_003_003", name: "接合部", count: 0 },
    ],
  },
  {
    id: "cat_004",
    name: "設備",
    children: [
      { id: "cat_004_001", name: "給排水", count: 0 },
      { id: "cat_004_002", name: "電気", count: 0 },
    ],
  },
];
